// <auto-generated />
using System;
using Infrastructure.Persistance.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201205002531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.Entities.MonopolyField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonopolyFieldListId")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonopolyFieldListId");

                    b.ToTable("MonopolyFields");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MonopolyField");
                });

            modelBuilder.Entity("Domain.Entities.MonopolyFieldList", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonopolyFieldLists");
                });

            modelBuilder.Entity("Domain.Entities.CornerField", b =>
                {
                    b.HasBaseType("Domain.Entities.MonopolyField");

                    b.HasDiscriminator().HasValue("CornerField");
                });

            modelBuilder.Entity("Domain.Entities.EventField", b =>
                {
                    b.HasBaseType("Domain.Entities.MonopolyField");

                    b.HasDiscriminator().HasValue("EventField");
                });

            modelBuilder.Entity("Domain.Entities.PropertyField", b =>
                {
                    b.HasBaseType("Domain.Entities.MonopolyField");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("EstatePrice")
                        .HasColumnType("int");

                    b.Property<int>("Mortage")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("Purschased")
                        .HasColumnType("bit");

                    b.Property<string>("RentCosts")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PropertyField");
                });

            modelBuilder.Entity("Domain.Entities.MonopolyField", b =>
                {
                    b.HasOne("Domain.Entities.MonopolyFieldList", null)
                        .WithMany("Fields")
                        .HasForeignKey("MonopolyFieldListId");
                });

            modelBuilder.Entity("Domain.Entities.MonopolyFieldList", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
